/*
 * Java Parallel Processing Framework.
 * Copyright (C) 2005-2007 JPPF Team.
 * http://www.jppf.org
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
package org.jppf.process;

import java.io.*;
import java.util.*;

import org.jppf.process.event.*;

/**
 * Wrapper around an external process started with {@link java.lang.ProcessBuilder ProcessBuilder}.
 * Instances of this class read the output ands error streams generated by the process and provide
 * a notification mechanism with separate events for the respective streams. 
 * @author Laurent Cohen
 */
public class ProcessWrapper
{
	/**
	 * Content of the standard output for the process.
	 */
	private StringBuilder standardOutput = new StringBuilder();
	/**
	 * Content of the error output for the process.
	 */
	private StringBuilder errorOutput = new StringBuilder();
	/**
	 * The process to handle.
	 */
	private Process process = null;
	/**
	 * List of listeners to this wrapper's output and error stream events.
	 */
	private List<ProcessWrapperEventListener> listeners = new ArrayList<ProcessWrapperEventListener>();

	/**
	 * Initialize this process handler with the specified process. 
	 * @param process the process to handle.
	 */
	public ProcessWrapper(Process process)
	{
		this.process = process;
		new StreamHandler(process.getInputStream(), standardOutput, true).start();
		new StreamHandler(process.getErrorStream(), errorOutput, false).start();
	}

	/**
	 * Get the content of the error output for the process.
	 * @return the content as a <code>StringBuilder</code> instance.
	 */
	public StringBuilder getErrorOutput()
	{
		return errorOutput;
	}

	/**
	 * Get the content of the standard output for the process.
	 * @return the content as a <code>StringBuilder</code> instance.
	 */
	public StringBuilder getStandardOutput()
	{
		return standardOutput;
	}

	/**
	 * Get the process to handle.
	 * @return a <code>Process</code> instance.
	 */
	public Process getProcess()
	{
		return process;
	}

	/**
	 * Add a listener to this process wrapper's listeners list.
	 * @param listener the listener to add.
	 */
	public void addProcessWrapperEventListener(ProcessWrapperEventListener listener)
	{
		listeners.add(listener);
	}

	/**
	 * Remove a listener from this process wrapper's listeners list.
	 * @param listener the listener to remove.
	 */
	public void removeProcessWrapperEventListener(ProcessWrapperEventListener listener)
	{
		listeners.remove(listener);
	}

	/**
	 * Notify all listeners that a stream event has occurred.
	 * @param output true if the event is for the outpuit stream, false if it is for the error stream.   
	 * @param content the text that written to the stream.
	 */
	protected synchronized void fireStreamEvent(boolean output, String content)
	{
		ProcessWrapperEvent event = new ProcessWrapperEvent(content);
		for (ProcessWrapperEventListener listener: listeners)
		{
			if (output) listener.outputStreamAltered(event);
			else listener.errorStreamAltered(event);
		}
	}

	/**
	 * Used to empty the standard or error output of a process, so as not to block the process.
	 */
	private class StreamHandler extends Thread
	{
		/**
		 * Flag to determine whether the event is for output or error stream.
		 */
		private boolean output = true;
		/**
		 * The stream to get the output from.
		 */
		private InputStream is = null;
		/**
		 * This is where the output goes.
		 */
		private StringBuilder sb = null;

		/**
		 * Initialize this handler with the specified stream and buffer receiving its content.
		 * @param is the stream where output is taken from.
		 * @param sb the buffer where the output is written.
		 * @param output true if this event is for an output stream, false for an error stream.
		 */
		public StreamHandler(InputStream is, StringBuilder sb, boolean output)
		{
			this.is = is;
			this.sb = sb;
			this.output = output;
		}

		/**
		 * Monitor the stream for avalaible data and write that data to the buffer.
		 * @see java.lang.Thread#run()
		 */
		public void run()
		{
			try
			{
				BufferedReader reader = new BufferedReader(new InputStreamReader(is));
				String s = "";
				while (s != null)
				{
					s = reader.readLine();
					if (s != null)
					{
						//System.out.println(s);
						sb.append(s).append("\n");
						fireStreamEvent(output, s);
					}
				}
				Thread.sleep(10);
			}
			catch(Throwable t)
			{
				t.printStackTrace();
			}
		}
	}
}
